{{- if (include "newrelic.areValuesValid" .) }}
{{- $licenseKey := include "newrelic.licenseKey" . -}}
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels: {{ include "newrelic.labels" . | indent 4 }}
  name: {{ template "newrelic.fullname" . }}
spec:
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      app: {{ template "newrelic.name" . }}
      release: {{.Release.Name }}
  template:
    metadata:
    {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8}}
    {{- end }}
      labels:
        app: {{ template "newrelic.name" . }}
        release: {{.Release.Name }}
        {{- if .Values.podLabels}}
        {{ toYaml .Values.podLabels }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "newrelic.serviceAccountName" . }}
      hostNetwork: true # This option is a requirement for the Infrastructure Agent to report the proper hostname in New Relic.
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ template "newrelic.name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            - name: ENDPOINT
              {{- if  $licenseKey }} 
                {{- if eq (substr 0 2 (include "newrelic.licenseKey" .)) "eu" }}
              value: "https://log-api.eu.newrelic.com/log/v1"
                {{- else }}
              value: "https://log-api.newrelic.com/log/v1"
                {{- end }}
              {{- else }}
              value: "https://log-api.newrelic.com/log/v1"
              {{- end }}
            - name: SOURCE
              value: "kubernetes"
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  {{- if $licenseKey }}
                  name: {{ template "newrelic.fullname" . }}-config
                  key: license
                  {{- else }}
                  name: {{ include "newrelic.customSecretName" . }}
                  key: {{ include "newrelic.customSecretKey" . }}
                  {{- end }}
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc
              readOnly: false
            - name: var
              mountPath: /var
              readOnly: false
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
      volumes:
        - name: fluentd-config
          configMap:
            name: {{ template "newrelic.fluentDConfig" . }}
        - name: var
          hostPath:
            path: /var
      {{- if $.Values.priorityClassName }}
      priorityClassName: {{ $.Values.priorityClassName }}
      {{- end }}
      {{- if $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
{{- end }}
