{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "newrelic.serviceAccountName" . }}
  labels:
    app: {{ template "newrelic.name" . }}
    chart: {{ template "newrelic.chart" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
{{- end -}}
